GET http://localhost:3004/api/notes

###
GET http://localhost:3004/api/notes/685c4695e1a6235abbcd7de3

###
POST http://localhost:3004/api/notes
content-type: application/json

{
    "content": "Nouvelle Note faites avec request.rest"
}

###
POST http://localhost:3004/api/notes
content-type: application/json

{
    "content": "lol",
    "important": true
}

###
DELETE http://localhost:3004/api/notes/685c46d9e1a6235abbcd7dea

###
PUT http://localhost:3004/api/notes/685c4643e1a6235abbcd7ddf
content-type: application/json

{
    "content": "J'ai mis à jour la note test",
    "important": "true"
}
